Src/Clients/WebUI/Controllers/ActorsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exam.Clients.WebUI.Common.Helpers.ApiTools;
using Exam.Clients.WebUI.Common.Models.Returnable.Actor;
using Exam.Clients.WebUI.Common.Models.Returnable.Film;
using Exam.Clients.WebUI.Common.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Exam.Clients.WebUI.Controllers
{
    public class ActorsController : Controller
    {
        private readonly IApiTools _apiTools;

        public ActorsController()
        {
            _apiTools = new ApiTools();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View((await _apiTools.FetchAsync<ActorsListReturnModel>("https://localhost:5001/api/actors/getall"))
                .Actors
                .TakeLast(10));
        }

        [HttpGet]
        public async Task<IActionResult> CreateOrUpdate(int id)
        {
            return View(await PrepareAsync(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate([FromForm] CreateOrUpdateActorViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            await PrepareAsync(model);

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            // TODO: To local Consts.cs.
            await _apiTools.DeleteAsync($"https://localhost:5001/api/actors/delete/{id}");

            return Ok();
        }

        #region Helpers

        private async Task<CreateOrUpdateActorViewModel> PrepareAsync(int id)
        {
            ActorReturnModel actor;
            IEnumerable<int> selectedFilms = null;

            if (id == 0)
            {
                actor = new ActorReturnModel();
            }
            else
            {
                actor = await _apiTools.FetchAsync<ActorReturnModel>($"https://localhost:5001/api/actors/get/{id}");
                selectedFilms =
                    (await _apiTools.FetchAsync<FilmsListReturnModel>(
                        $"https://localhost:5001/api/films/getallbyactor/{id}")).Films.Select(x => x.FilmId);
            }

            return new CreateOrUpdateActorViewModel
            {
                Actor = actor,

                Films = (await _apiTools.FetchAsync<FilmsListReturnModel>("https://localhost:5001/api/films/getall"))
                    .Films
                    .TakeLast(10)
                    .Select(x => new SelectListItem
                    {
                        Value = x.FilmId.ToString(),
                        Text = $"{x.Title} ({x.PublishYear.Year})"
                    }),

                SelectedFilms = selectedFilms
            };
        }

        private async Task<IEnumerable<FilmReturnModel>> FetchSelectedFilmsAsync(CreateOrUpdateActorViewModel model)
        {
            var actors = new List<FilmReturnModel>();

            if (model.IsNopeFilms) return actors;
            if (model.SelectedFilms == null) return actors;

            foreach (var selectedFilmId in model.SelectedFilms)
                actors.Add(await _apiTools.FetchAsync<FilmReturnModel>(
                    $"https://localhost:5001/api/films/get/{selectedFilmId}"));

            return actors;
        }

        private async Task PrepareAsync(CreateOrUpdateActorViewModel model)
        {
            var selectedFilms = await FetchSelectedFilmsAsync(model);

            if (model.Actor.ActorId == 0)
                await _apiTools.PostAsync<ActorReturnModel>("https://localhost:5001/api/actors/create",
                    new {model.Actor.FirstName, model.Actor.LastName, model.Actor.Birthday, Films = selectedFilms});
            else
                await _apiTools.PostAsync<ActorReturnModel>("https://localhost:5001/api/actors/update",
                    new
                    {
                        model.Actor.ActorId,
                        model.Actor.FirstName,
                        model.Actor.LastName,
                        model.Actor.Birthday,
                        Films = selectedFilms
                    });
        }

        #endregion
    }
}

Src/Clients/WebUI/Controllers/FilmsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Exam.Clients.WebUI.Common.Helpers.ApiTools;
using Exam.Clients.WebUI.Common.Models.Returnable.Actor;
using Exam.Clients.WebUI.Common.Models.Returnable.Film;
using Exam.Clients.WebUI.Common.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Exam.Clients.WebUI.Controllers
{
    public class FilmsController : Controller
    {
        private readonly IApiTools _apiTools;

        public FilmsController()
        {
            // TODO: DI.
            _apiTools = new ApiTools();
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // TODO: To local Consts.cs.

            return View((await _apiTools.FetchAsync<FilmsListReturnModel>("https://localhost:5001/api/films/getall"))
                .Films
                .TakeLast(10));
        }

        [HttpGet]
        public async Task<IActionResult> CreateOrUpdate(int id)
        {
            return View(await PrepareAsync(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrUpdate([FromForm] CreateOrUpdateFilmViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            await PrepareAsync(model);

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            // TODO: To local Consts.cs.
            await _apiTools.DeleteAsync($"https://localhost:5001/api/films/delete/{id}");

            return Ok();
        }

        #region Helpers

        private async Task<CreateOrUpdateFilmViewModel> PrepareAsync(int id)
        {
            FilmReturnModel film;
            IEnumerable<int> selectedActors = null;

            if (id == 0)
            {
                film = new FilmReturnModel();
            }
            else
            {
                film = await _apiTools.FetchAsync<FilmReturnModel>($"https://localhost:5001/api/films/get/{id}");
                selectedActors =
                    (await _apiTools.FetchAsync<ActorsListReturnModel>(
                        $"https://localhost:5001/api/actors/getallbyfilm/{id}")).Actors.Select(x => x.ActorId);
            }

            return new CreateOrUpdateFilmViewModel
            {
                Film = film,

                Actors = (await _apiTools.FetchAsync<ActorsListReturnModel>("https://localhost:5001/api/actors/getall"))
                    .Actors
                    .TakeLast(10)
                    .Select(x => new SelectListItem
                    {
                        Value = x.ActorId.ToString(),
                        Text = $"{x.FirstName} {x.LastName}"
                    }),

                SelectedActors = selectedActors
            };
        }

        private async Task<IEnumerable<ActorReturnModel>> FetchSelectedActorsAsync(CreateOrUpdateFilmViewModel model)
        {
            var actors = new List<ActorReturnModel>();

            if (model.IsNopeActors) return actors;
            if (model.SelectedActors == null) return actors;

            foreach (var selectedActorId in model.SelectedActors)
                actors.Add(await _apiTools.FetchAsync<ActorReturnModel>(
                    $"https://localhost:5001/api/actors/get/{selectedActorId}"));

            return actors;
        }

        private async Task PrepareAsync(CreateOrUpdateFilmViewModel model)
        {
            var selectedActors = await FetchSelectedActorsAsync(model);

            if (model.Film.FilmId == 0)
                await _apiTools.PostAsync<FilmReturnModel>("https://localhost:5001/api/films/create",
                    new {model.Film.Title, model.Film.PublishYear, model.Film.Description, Actors = selectedActors});
            else
                await _apiTools.PostAsync<FilmReturnModel>("https://localhost:5001/api/films/update",
                    new
                    {
                        model.Film.FilmId,
                        model.Film.Title,
                        model.Film.PublishYear,
                        model.Film.Description,
                        Actors = selectedActors
                    });
        }

        #endregion
    }
}

Src/Clients/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Voting System (Exam)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    @RenderSection("Styles", false)
</head>
<body>

<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Voting System</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse d-sm-inline-flex">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Films" asp-action="Index">Films</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Actors" asp-action="Index">Actors</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" asp-controller="Genres" asp-action="Index">Genres</a>
                    </li>
                </ul>

                @*<ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Right-side</a>
                    </li>
                </ul>*@

            </div>

        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-5">
        @RenderBody()
    </main>
</div>

<footer class="footer text-muted">
    <div class="container text-center">
        <div class="row">
            <div class="col-md-12 pb-3">
                <hr>
                Exam ASP.NET Core
            </div>
        </div>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", false)

</body>
</html>